a = input('Digite algo:')
print('Aqui estão algumas informações sobre o valor acima:')
print('O tipo primitivo desse valor é:', type(a))
print('Há espaços?', a.isspace())
print('Letras maiúsculas?', a.isupper())
print('Letras minúsculas?', a.islower())
print('É alfabeto?', a.isalpha())
print('São números?', a.isnumeric())
print('É alfanumérico?', a.isalnum())
print('Está capitalizada?', a.istitle())
